sources:
  my_athena:
    type: athena
    region_name: us-east-1
    database: my_database
    s3_output_location: s3://my-bucket/athena-results/
    aws_access_key_id: YOUR_ACCESS_KEY
    aws_secret_access_key: YOUR_SECRET_KEY

  my_postgres:
    type: postgres
    host: localhost
    port: 5432
    database: my_database
    username: postgres
    password: password

  my_mysql:
    type: mysql
    host: localhost
    port: 3306
    database: my_database
    username: root
    password: password

  my_sqlserver:
    type: sqlserver
    host: localhost
    port: 1433
    database: my_database
    username: sa
    password: YourPassword123
    driver: "{ODBC Driver 17 for SQL Server}"

  my_sqlite:
    type: sqlite
    database_path: /path/to/database.db

  my_opensearch:
    type: opensearch
    hosts:
      - localhost:9200
    username: admin
    password: admin
    use_ssl: true
    verify_certs: false

  my_solr:
    type: solr
    url: http://localhost:8983/solr/my_core
    timeout: 10

  my_cassandra:
    type: cassandra
    hosts:
      - localhost
    port: 9042
    keyspace: my_keyspace
    username: cassandra
    password: cassandra

  my_kafka:
    type: kafka
    bootstrap_servers:
      - localhost:9092
    topic: my_topic
    group_id: my_consumer_group
    auto_offset_reset: earliest

  my_sns:
    type: sns
    region_name: us-east-1
    topic_arn: arn:aws:sns:us-east-1:123456789012:my-topic
    aws_access_key_id: YOUR_ACCESS_KEY
    aws_secret_access_key: YOUR_SECRET_KEY

  my_sqs:
    type: sqs
    region_name: us-east-1
    queue_url: https://sqs.us-east-1.amazonaws.com/123456789012/my-queue
    aws_access_key_id: YOUR_ACCESS_KEY
    aws_secret_access_key: YOUR_SECRET_KEY

  my_rabbitmq:
    type: rabbitmq
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual_host: /
    queue: my_queue
    exchange: ""
